version: '3'
services:
  thingspro-demo:
    image: thingspro-demo:${ARCH}
    networks:
      - appservice
    environment:
      - APPMAN_HOST_IP=172.31.8.1
    volumes:
      - /var/run/tpfunc:/host/run/tpfunc